server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulishop-search
# 禁用thymeleaf的缓存，实现即时刷新
  thymeleaf:
    cache: false

#    jackson:
#      date-format: yyyy-MM-dd HH:mm:ss