spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G3Ddd5D8B91hAA8Fgsc
      secret-key: Nj9eK3FQ24u7FKvEoDosoCN3befUzk
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: summersky-guli-file  #在阿里创建的bucket的名称

  application:
    name: gulishop-third-party  #微服务注册到注册中心的名称

server:
  port: 30000
